### ISSUE TITLE
Error with async spamming after running console command

### ISSUE THREAD

**Issue by Srlion** [CFC-Servers/GLuaTest#63]
[goobie_sql.zip](https://github.com/user-attachments/files/17284521/goobie_sql.zip)

start server

wait everything is done, run: gluatest_run_tests, wait couple of seconds and get a boomy woomy

```
    Context:
      _______________________________________

     |
 276 |     end
 277 | },
 278 | {
 279 |     name = "FetchOneErrorAsync",
 280 |     async = true,
 281 |     func = function() <- Timeout
     |_______________________________________


[gluatest] addons/gluatest/lua/gluatest/runner/runner.lua:201: attempt to index upvalue 'testGroup' (a nil value)
  1. testComplete - addons/gluatest/lua/gluatest/runner/runner.lua:201
   2. unknown - addons/gluatest/lua/gluatest/runner/runner.lua:264

Timer Failed! [GLuaTest_AsyncTimeout_case58][@addons/gluatest/lua/gluatest/runner/runner.lua (line 260)]
```

**Comment by brandonsturgeon** [comment]
Thanks for the report!

The issue here was because the tests you marked as `async` were actually operating synchronously (i.e. they called `done()` as soon as the test case was executed).

This should be acceptable behavior in GLuaTest, and I believe I've addressed the issue in [`0.32.2`](https://github.com/CFC-Servers/GLuaTest/releases/tag/0.32.2)

In your case specifically, you could:
- Update GLuaTest and leave the tests as-is
- Convert the tests to be synchronous tests

I sent you an example of doing the latter; because the `sql` library won't actually be async, I suspect you'll prefer this option 👍
